spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/aiwork?useSSL=false
    username: root
    password: 65513599
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
server:
  port: 9001

